site:
  title: TaucherDoc  Demo Site
  # the 404 page and sitemap files only get generated when the url property is set
  url: taucherdoc.org/docs
content:
  sources:
  - url: https://github.com/ukubauka/TaucherDoc.git
    branches: Antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
